version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: ./.cicd/docker/Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://user:password@database:3306/mydb

  database:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: