services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - './docker/conf/nginx:/etc/nginx/conf.d'
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:16.6
    environment:
      POSTGRES_DB: online_shop_db
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: 123
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "54323:5432"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # основной порт
      - "15672:15672"    # web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: