order_controllers:
    resource:
        path: ../src/Order/Controller/
        namespace: App\Order\Controller
    type: attribute

cart_controllers:
    resource:
        path: ../src/Cart/Controller/
        namespace: App\Cart\Controller
    type: attribute

user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute

login_check:
    path: /api/login
    methods: [POST]

